package com.api.genshinimpact.service;

import com.api.genshinimpact.dto.AchievementsDTO;
import com.api.genshinimpact.entities.Achievements;
import com.api.genshinimpact.entities.Characters;
import com.api.genshinimpact.repository.AchievementsRepository;
import com.api.genshinimpact.service.exceptions.EntityNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.NoSuchElementException;

@Service
public class CrudAchievementsService {
    private final AchievementsRepository achievementsRepository;

    @Autowired
    public CrudAchievementsService(AchievementsRepository achievementsRepository){
        this.achievementsRepository = achievementsRepository;
    }

    public void insertData(){
        Achievements contos_de_loucura_monstruosa = new Achievements(1, "Maravilhas do Mundo", "Contos de Loucura Monstruosa", "Colete toa a série Contos da Rua Toki", 5, 2855);
/*
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);
        Achievements  = new Achievements(1, "Maravilhas do Mundo", "", "", 0, 2855);


        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);
        Achievements  = new Achievements(1, "Memórias do Coração", "", "", 0, 540);

        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série I", "", "", 0, 30);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série I", "", "", 0, 30);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série I", "", "", 0, 30);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série I", "", "", 0, 30);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série I", "", "", 0, 30);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série I", "", "", 0, 30);


        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série II", "", "", 0, 25);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série II", "", "", 0, 25);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série II", "", "", 0, 25);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série II", "", "", 0, 25);
        Achievements  = new Achievements(1, "Andarilho do Mundo Mortal: Série II", "", "", 0, 25);*/

        this.achievementsRepository.save(contos_de_loucura_monstruosa);
        System.out.println("Achievements save in database");
    }

    //----------- SELECIONAR DADOS DA TABELA ACHIEVEMENTS------
    public void selectData(){
        Iterable<Achievements> achievements = this.achievementsRepository.findAll();
        for (Achievements achievement : achievements){
            System.out.println(achievement);
        }
    };
    public List<Achievements>findALL(){
        return (List<Achievements>) achievementsRepository.findAll();
    }
    public AchievementsDTO findById(Integer id){
            Achievements obj = achievementsRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("Achievement not found with id: " + id));
            return new AchievementsDTO(obj);
    }


/*
	public Movie findById(Long id) {
		return movieRepository.findById(id).orElseThrow(
				() -> new EntityNotFoundException("Id not found " + id));
	}

		public Movie findById(Long id) {
		return movieRepository.findById(id).orElseThrow(
				() -> new EntityNotFoundException("Id not found " + id));
	}
* */
}